/** Static ISO-3166-1 alpha-2 country options for FoW Country catalog. */

export type FowCountryOption = { id: string; label: string }

/**
 * FoW alpha parquet partitions confirmed missing on Source Cooperative
 * (`results-by-admin-conf/admin:country_code=XX/...` → 404).
 * Prefer FTW live / map detect for these instead of an empty FoW scan.
 */
export const FOW_MISSING_CATALOG_ISOS: ReadonlySet<string> = new Set([
  'AE', // United Arab Emirates — no UnitedArabEmirates.parquet / AE.parquet
])

export function isFowCatalogMissing(iso: string | null | undefined): boolean {
  const code = String(iso || '')
    .trim()
    .toUpperCase()
  return code.length === 2 && FOW_MISSING_CATALOG_ISOS.has(code)
}

export const FOW_COUNTRY_OPTIONS: FowCountryOption[] = [
  { id: '', label: 'All countries (slow FoW scan)' },
  { id: 'AF', label: "Afghanistan (AF)" },
  { id: 'AX', label: "Åland Islands (AX)" },
  { id: 'AL', label: "Albania (AL)" },
  { id: 'DZ', label: "Algeria (DZ)" },
  { id: 'AS', label: "American Samoa (AS)" },
  { id: 'AD', label: "Andorra (AD)" },
  { id: 'AO', label: "Angola (AO)" },
  { id: 'AI', label: "Anguilla (AI)" },
  { id: 'AQ', label: "Antarctica (AQ)" },
  { id: 'AG', label: "Antigua and Barbuda (AG)" },
  { id: 'AR', label: "Argentina (AR)" },
  { id: 'AM', label: "Armenia (AM)" },
  { id: 'AW', label: "Aruba (AW)" },
  { id: 'AU', label: "Australia (AU)" },
  { id: 'AT', label: "Austria (AT)" },
  { id: 'AZ', label: "Azerbaijan (AZ)" },
  { id: 'BS', label: "Bahamas (BS)" },
  { id: 'BH', label: "Bahrain (BH)" },
  { id: 'BD', label: "Bangladesh (BD)" },
  { id: 'BB', label: "Barbados (BB)" },
  { id: 'BY', label: "Belarus (BY)" },
  { id: 'BE', label: "Belgium (BE)" },
  { id: 'BZ', label: "Belize (BZ)" },
  { id: 'BJ', label: "Benin (BJ)" },
  { id: 'BM', label: "Bermuda (BM)" },
  { id: 'BT', label: "Bhutan (BT)" },
  { id: 'BO', label: "Bolivia, Plurinational State of (BO)" },
  { id: 'BQ', label: "Bonaire, Sint Eustatius and Saba (BQ)" },
  { id: 'BA', label: "Bosnia and Herzegovina (BA)" },
  { id: 'BW', label: "Botswana (BW)" },
  { id: 'BV', label: "Bouvet Island (BV)" },
  { id: 'BR', label: "Brazil (BR)" },
  { id: 'IO', label: "British Indian Ocean Territory (IO)" },
  { id: 'BN', label: "Brunei Darussalam (BN)" },
  { id: 'BG', label: "Bulgaria (BG)" },
  { id: 'BF', label: "Burkina Faso (BF)" },
  { id: 'BI', label: "Burundi (BI)" },
  { id: 'CV', label: "Cabo Verde (CV)" },
  { id: 'KH', label: "Cambodia (KH)" },
  { id: 'CM', label: "Cameroon (CM)" },
  { id: 'CA', label: "Canada (CA)" },
  { id: 'KY', label: "Cayman Islands (KY)" },
  { id: 'CF', label: "Central African Republic (CF)" },
  { id: 'TD', label: "Chad (TD)" },
  { id: 'CL', label: "Chile (CL)" },
  { id: 'CN', label: "China (CN)" },
  { id: 'CX', label: "Christmas Island (CX)" },
  { id: 'CC', label: "Cocos (Keeling) Islands (CC)" },
  { id: 'CO', label: "Colombia (CO)" },
  { id: 'KM', label: "Comoros (KM)" },
  { id: 'CG', label: "Congo (CG)" },
  { id: 'CD', label: "Congo, Democratic Republic of the (CD)" },
  { id: 'CK', label: "Cook Islands (CK)" },
  { id: 'CR', label: "Costa Rica (CR)" },
  { id: 'CI', label: "Côte d'Ivoire (CI)" },
  { id: 'HR', label: "Croatia (HR)" },
  { id: 'CU', label: "Cuba (CU)" },
  { id: 'CW', label: "Curaçao (CW)" },
  { id: 'CY', label: "Cyprus (CY)" },
  { id: 'CZ', label: "Czechia (CZ)" },
  { id: 'DK', label: "Denmark (DK)" },
  { id: 'DJ', label: "Djibouti (DJ)" },
  { id: 'DM', label: "Dominica (DM)" },
  { id: 'DO', label: "Dominican Republic (DO)" },
  { id: 'EC', label: "Ecuador (EC)" },
  { id: 'EG', label: "Egypt (EG)" },
  { id: 'SV', label: "El Salvador (SV)" },
  { id: 'GQ', label: "Equatorial Guinea (GQ)" },
  { id: 'ER', label: "Eritrea (ER)" },
  { id: 'EE', label: "Estonia (EE)" },
  { id: 'SZ', label: "Eswatini (SZ)" },
  { id: 'ET', label: "Ethiopia (ET)" },
  { id: 'FK', label: "Falkland Islands (Malvinas) (FK)" },
  { id: 'FO', label: "Faroe Islands (FO)" },
  { id: 'FJ', label: "Fiji (FJ)" },
  { id: 'FI', label: "Finland (FI)" },
  { id: 'FR', label: "France (FR)" },
  { id: 'GF', label: "French Guiana (GF)" },
  { id: 'PF', label: "French Polynesia (PF)" },
  { id: 'TF', label: "French Southern Territories (TF)" },
  { id: 'GA', label: "Gabon (GA)" },
  { id: 'GM', label: "Gambia (GM)" },
  { id: 'GE', label: "Georgia (GE)" },
  { id: 'DE', label: "Germany (DE)" },
  { id: 'GH', label: "Ghana (GH)" },
  { id: 'GI', label: "Gibraltar (GI)" },
  { id: 'GR', label: "Greece (GR)" },
  { id: 'GL', label: "Greenland (GL)" },
  { id: 'GD', label: "Grenada (GD)" },
  { id: 'GP', label: "Guadeloupe (GP)" },
  { id: 'GU', label: "Guam (GU)" },
  { id: 'GT', label: "Guatemala (GT)" },
  { id: 'GG', label: "Guernsey (GG)" },
  { id: 'GN', label: "Guinea (GN)" },
  { id: 'GW', label: "Guinea-Bissau (GW)" },
  { id: 'GY', label: "Guyana (GY)" },
  { id: 'HT', label: "Haiti (HT)" },
  { id: 'HM', label: "Heard Island and McDonald Islands (HM)" },
  { id: 'VA', label: "Holy See (VA)" },
  { id: 'HN', label: "Honduras (HN)" },
  { id: 'HK', label: "Hong Kong (HK)" },
  { id: 'HU', label: "Hungary (HU)" },
  { id: 'IS', label: "Iceland (IS)" },
  { id: 'IN', label: "India (IN)" },
  { id: 'ID', label: "Indonesia (ID)" },
  { id: 'IR', label: "Iran, Islamic Republic of (IR)" },
  { id: 'IQ', label: "Iraq (IQ)" },
  { id: 'IE', label: "Ireland (IE)" },
  { id: 'IM', label: "Isle of Man (IM)" },
  { id: 'IL', label: "Israel (IL)" },
  { id: 'IT', label: "Italy (IT)" },
  { id: 'JM', label: "Jamaica (JM)" },
  { id: 'JP', label: "Japan (JP)" },
  { id: 'JE', label: "Jersey (JE)" },
  { id: 'JO', label: "Jordan (JO)" },
  { id: 'KZ', label: "Kazakhstan (KZ)" },
  { id: 'KE', label: "Kenya (KE)" },
  { id: 'KI', label: "Kiribati (KI)" },
  { id: 'KP', label: "Korea, Democratic People's Republic of (KP)" },
  { id: 'KR', label: "Korea, Republic of (KR)" },
  { id: 'KW', label: "Kuwait (KW)" },
  { id: 'KG', label: "Kyrgyzstan (KG)" },
  { id: 'LA', label: "Lao People's Democratic Republic (LA)" },
  { id: 'LV', label: "Latvia (LV)" },
  { id: 'LB', label: "Lebanon (LB)" },
  { id: 'LS', label: "Lesotho (LS)" },
  { id: 'LR', label: "Liberia (LR)" },
  { id: 'LY', label: "Libya (LY)" },
  { id: 'LI', label: "Liechtenstein (LI)" },
  { id: 'LT', label: "Lithuania (LT)" },
  { id: 'LU', label: "Luxembourg (LU)" },
  { id: 'MO', label: "Macao (MO)" },
  { id: 'MG', label: "Madagascar (MG)" },
  { id: 'MW', label: "Malawi (MW)" },
  { id: 'MY', label: "Malaysia (MY)" },
  { id: 'MV', label: "Maldives (MV)" },
  { id: 'ML', label: "Mali (ML)" },
  { id: 'MT', label: "Malta (MT)" },
  { id: 'MH', label: "Marshall Islands (MH)" },
  { id: 'MQ', label: "Martinique (MQ)" },
  { id: 'MR', label: "Mauritania (MR)" },
  { id: 'MU', label: "Mauritius (MU)" },
  { id: 'YT', label: "Mayotte (YT)" },
  { id: 'MX', label: "Mexico (MX)" },
  { id: 'FM', label: "Micronesia, Federated States of (FM)" },
  { id: 'MD', label: "Moldova, Republic of (MD)" },
  { id: 'MC', label: "Monaco (MC)" },
  { id: 'MN', label: "Mongolia (MN)" },
  { id: 'ME', label: "Montenegro (ME)" },
  { id: 'MS', label: "Montserrat (MS)" },
  { id: 'MA', label: "Morocco (MA)" },
  { id: 'MZ', label: "Mozambique (MZ)" },
  { id: 'MM', label: "Myanmar (MM)" },
  { id: 'NA', label: "Namibia (NA)" },
  { id: 'NR', label: "Nauru (NR)" },
  { id: 'NP', label: "Nepal (NP)" },
  { id: 'NL', label: "Netherlands, Kingdom of the (NL)" },
  { id: 'NC', label: "New Caledonia (NC)" },
  { id: 'NZ', label: "New Zealand (NZ)" },
  { id: 'NI', label: "Nicaragua (NI)" },
  { id: 'NE', label: "Niger (NE)" },
  { id: 'NG', label: "Nigeria (NG)" },
  { id: 'NU', label: "Niue (NU)" },
  { id: 'NF', label: "Norfolk Island (NF)" },
  { id: 'MK', label: "North Macedonia (MK)" },
  { id: 'MP', label: "Northern Mariana Islands (MP)" },
  { id: 'NO', label: "Norway (NO)" },
  { id: 'OM', label: "Oman (OM)" },
  { id: 'PK', label: "Pakistan (PK)" },
  { id: 'PW', label: "Palau (PW)" },
  { id: 'PS', label: "Palestine, State of (PS)" },
  { id: 'PA', label: "Panama (PA)" },
  { id: 'PG', label: "Papua New Guinea (PG)" },
  { id: 'PY', label: "Paraguay (PY)" },
  { id: 'PE', label: "Peru (PE)" },
  { id: 'PH', label: "Philippines (PH)" },
  { id: 'PN', label: "Pitcairn (PN)" },
  { id: 'PL', label: "Poland (PL)" },
  { id: 'PT', label: "Portugal (PT)" },
  { id: 'PR', label: "Puerto Rico (PR)" },
  { id: 'QA', label: "Qatar (QA)" },
  { id: 'RE', label: "Réunion (RE)" },
  { id: 'RO', label: "Romania (RO)" },
  { id: 'RU', label: "Russian Federation (RU)" },
  { id: 'RW', label: "Rwanda (RW)" },
  { id: 'BL', label: "Saint Barthélemy (BL)" },
  { id: 'SH', label: "Saint Helena, Ascension and Tristan da Cunha (SH)" },
  { id: 'KN', label: "Saint Kitts and Nevis (KN)" },
  { id: 'LC', label: "Saint Lucia (LC)" },
  { id: 'MF', label: "Saint Martin (French part) (MF)" },
  { id: 'PM', label: "Saint Pierre and Miquelon (PM)" },
  { id: 'VC', label: "Saint Vincent and the Grenadines (VC)" },
  { id: 'WS', label: "Samoa (WS)" },
  { id: 'SM', label: "San Marino (SM)" },
  { id: 'ST', label: "Sao Tome and Principe (ST)" },
  { id: 'SA', label: "Saudi Arabia (SA)" },
  { id: 'SN', label: "Senegal (SN)" },
  { id: 'RS', label: "Serbia (RS)" },
  { id: 'SC', label: "Seychelles (SC)" },
  { id: 'SL', label: "Sierra Leone (SL)" },
  { id: 'SG', label: "Singapore (SG)" },
  { id: 'SX', label: "Sint Maarten (Dutch part) (SX)" },
  { id: 'SK', label: "Slovakia (SK)" },
  { id: 'SI', label: "Slovenia (SI)" },
  { id: 'SB', label: "Solomon Islands (SB)" },
  { id: 'SO', label: "Somalia (SO)" },
  { id: 'ZA', label: "South Africa (ZA)" },
  { id: 'GS', label: "South Georgia and the South Sandwich Islands (GS)" },
  { id: 'SS', label: "South Sudan (SS)" },
  { id: 'ES', label: "Spain (ES)" },
  { id: 'LK', label: "Sri Lanka (LK)" },
  { id: 'SD', label: "Sudan (SD)" },
  { id: 'SR', label: "Suriname (SR)" },
  { id: 'SJ', label: "Svalbard and Jan Mayen (SJ)" },
  { id: 'SE', label: "Sweden (SE)" },
  { id: 'CH', label: "Switzerland (CH)" },
  { id: 'SY', label: "Syrian Arab Republic (SY)" },
  { id: 'TW', label: "Taiwan, Province of China (TW)" },
  { id: 'TJ', label: "Tajikistan (TJ)" },
  { id: 'TZ', label: "Tanzania, United Republic of (TZ)" },
  { id: 'TH', label: "Thailand (TH)" },
  { id: 'TL', label: "Timor-Leste (TL)" },
  { id: 'TG', label: "Togo (TG)" },
  { id: 'TK', label: "Tokelau (TK)" },
  { id: 'TO', label: "Tonga (TO)" },
  { id: 'TT', label: "Trinidad and Tobago (TT)" },
  { id: 'TN', label: "Tunisia (TN)" },
  { id: 'TR', label: "Türkiye (TR)" },
  { id: 'TM', label: "Turkmenistan (TM)" },
  { id: 'TC', label: "Turks and Caicos Islands (TC)" },
  { id: 'TV', label: "Tuvalu (TV)" },
  { id: 'UG', label: "Uganda (UG)" },
  { id: 'UA', label: "Ukraine (UA)" },
  { id: 'AE', label: "United Arab Emirates (AE) — FoW catalog missing, uses FTW" },
  { id: 'GB', label: "United Kingdom of Great Britain and Northern Ireland (GB)" },
  { id: 'UM', label: "United States Minor Outlying Islands (UM)" },
  { id: 'US', label: "United States of America (US)" },
  { id: 'UY', label: "Uruguay (UY)" },
  { id: 'UZ', label: "Uzbekistan (UZ)" },
  { id: 'VU', label: "Vanuatu (VU)" },
  { id: 'VE', label: "Venezuela, Bolivarian Republic of (VE)" },
  { id: 'VN', label: "Viet Nam (VN)" },
  { id: 'VG', label: "Virgin Islands (British) (VG)" },
  { id: 'VI', label: "Virgin Islands (U.S.) (VI)" },
  { id: 'WF', label: "Wallis and Futuna (WF)" },
  { id: 'EH', label: "Western Sahara (EH)" },
  { id: 'YE', label: "Yemen (YE)" },
  { id: 'ZM', label: "Zambia (ZM)" },
  { id: 'ZW', label: "Zimbabwe (ZW)" },
]
