import ExcelJS from 'exceljs'
import type { SarFloodReportPayload } from './sarFloodReportTypes'

function styleHeader(cell: ExcelJS.Cell): void {
  cell.font = { bold: true, color: { argb: 'FFFFFFFF' } }
  cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF064E3B' } }
  cell.alignment = { vertical: 'middle', wrapText: true }
}

function autoWidth(ws: ExcelJS.Worksheet, cols: number): void {
  for (let c = 1; c <= cols; c += 1) {
    let max = 12
    ws.eachRow(row => {
      const v = row.getCell(c).value
      const len = v == null ? 0 : String(v).length
      max = Math.max(max, Math.min(len + 2, 48))
    })
    ws.getColumn(c).width = max
  }
}

function buildSummarySheet(wb: ExcelJS.Workbook, p: SarFloodReportPayload): void {
  const ws = wb.addWorksheet('Summary')
  ws.getCell(1, 1).value = 'SAR Flood Intelligence Report — Summary'
  styleHeader(ws.getCell(1, 1))
  ws.mergeCells(1, 1, 1, 2)

  const rows: Array<[string, string]> = [
    ['Project', p.projectName],
    ['Generated by', p.generatedBy],
    ['Generated at', p.generatedAt],
    ['AOI', p.aoiName],
    ['Area', `${p.areaHa.toFixed(2)} ha`],
    ['Centroid', p.centroidLabel],
    ['CRS', p.crs],
    ['Sensor', p.sensorLabel],
    ['Modality', p.modality],
    ['Mode', p.mode],
    ['Pre date', p.preDate],
    ['Post date', p.postDate],
    ['VV threshold', `${p.thresholdDb} dB`],
    ['Resolution', p.resolution],
  ]
  let r = 3
  for (const [k, v] of rows) {
    ws.getCell(r, 1).value = k
    ws.getCell(r, 1).font = { bold: true }
    ws.getCell(r, 2).value = v
    r += 1
  }
  r += 1
  ws.getCell(r, 1).value = 'Executive overview'
  styleHeader(ws.getCell(r, 1))
  ws.mergeCells(r, 1, r, 2)
  r += 1
  ws.getCell(r, 1).value = p.executive.projectOverview
  ws.mergeCells(r, 1, r, 2)
  ws.getCell(r, 1).alignment = { wrapText: true }
  ws.getRow(r).height = 60
  autoWidth(ws, 2)
}

function buildClassSheet(wb: ExcelJS.Workbook, p: SarFloodReportPayload): void {
  const ws = wb.addWorksheet('Class Composition')
  const table = p.tables.find(t => /composition/i.test(t.title)) ?? p.tables[1]
  if (!table) {
    ws.getCell(1, 1).value = 'No class composition table'
    return
  }
  ws.getCell(1, 1).value = table.title
  styleHeader(ws.getCell(1, 1))
  ws.mergeCells(1, 1, 1, table.headers.length)
  table.headers.forEach((h, i) => {
    const cell = ws.getCell(3, i + 1)
    cell.value = h
    styleHeader(cell)
  })
  table.rows.forEach((row, ri) => {
    row.forEach((val, ci) => {
      ws.getCell(4 + ri, ci + 1).value = val
    })
  })
  autoWidth(ws, table.headers.length)
}

function buildStatsSheet(wb: ExcelJS.Workbook, p: SarFloodReportPayload): void {
  const ws = wb.addWorksheet('Flood Statistics')
  const table = p.tables.find(t => /summary/i.test(t.title)) ?? p.tables[0]
  if (!table) return
  ws.getCell(1, 1).value = table.title
  styleHeader(ws.getCell(1, 1))
  ws.mergeCells(1, 1, 1, 2)
  table.headers.forEach((h, i) => {
    const cell = ws.getCell(3, i + 1)
    cell.value = h
    styleHeader(cell)
  })
  table.rows.forEach((row, ri) => {
    row.forEach((val, ci) => {
      ws.getCell(4 + ri, ci + 1).value = val
    })
  })
  autoWidth(ws, 2)

  // Depth / risk if present
  let start = 4 + table.rows.length + 2
  for (const extra of p.tables.filter(t => /depth|risk/i.test(t.title))) {
    ws.getCell(start, 1).value = extra.title
    styleHeader(ws.getCell(start, 1))
    ws.mergeCells(start, 1, start, 2)
    start += 1
    extra.headers.forEach((h, i) => {
      const cell = ws.getCell(start, i + 1)
      cell.value = h
      styleHeader(cell)
    })
    start += 1
    extra.rows.forEach(row => {
      row.forEach((val, ci) => {
        ws.getCell(start, ci + 1).value = val
      })
      start += 1
    })
    start += 1
  }
}

function buildMethodologySheet(wb: ExcelJS.Workbook, p: SarFloodReportPayload): void {
  const ws = wb.addWorksheet('Methodology')
  ws.getCell(1, 1).value = 'Methodology'
  styleHeader(ws.getCell(1, 1))
  ws.mergeCells(1, 1, 1, 2)
  ws.getCell(3, 1).value = p.methodologyNotes
  ws.mergeCells(3, 1, 3, 2)
  ws.getCell(3, 1).alignment = { wrapText: true }
  ws.getRow(3).height = 80

  ws.getCell(5, 1).value = 'Data quality & limitations'
  styleHeader(ws.getCell(5, 1))
  ws.mergeCells(5, 1, 5, 2)
  ws.getCell(6, 1).value = p.dataQualityNotes
  ws.mergeCells(6, 1, 6, 2)
  ws.getCell(6, 1).alignment = { wrapText: true }
  ws.getRow(6).height = 80

  ws.getCell(8, 1).value = 'Recommendations'
  styleHeader(ws.getCell(8, 1))
  ws.mergeCells(8, 1, 8, 2)
  p.recommendations.forEach((rec, i) => {
    ws.getCell(9 + i, 1).value = `${i + 1}.`
    ws.getCell(9 + i, 2).value = rec
  })
  autoWidth(ws, 2)
}

function buildMapIndexSheet(wb: ExcelJS.Workbook, p: SarFloodReportPayload): void {
  const ws = wb.addWorksheet('Map Index')
  ;['Map', 'Available', 'Legend', 'Stats'].forEach((h, i) => {
    const cell = ws.getCell(1, i + 1)
    cell.value = h
    styleHeader(cell)
  })
  p.snapshots.forEach((snap, i) => {
    const r = i + 2
    ws.getCell(r, 1).value = snap.title
    ws.getCell(r, 2).value = snap.available ? 'Yes' : 'No'
    ws.getCell(r, 3).value = snap.legendText
    ws.getCell(r, 4).value = snap.stats.map(s => `${s.label}: ${s.value}`).join(' · ')
  })
  autoWidth(ws, 4)
}

export async function buildSarFloodReportWorkbook(
  payload: SarFloodReportPayload,
): Promise<ExcelJS.Workbook> {
  const wb = new ExcelJS.Workbook()
  wb.creator = 'AgroCloud SAR Flood Intelligence'
  wb.created = new Date()
  buildSummarySheet(wb, payload)
  buildStatsSheet(wb, payload)
  buildClassSheet(wb, payload)
  buildMethodologySheet(wb, payload)
  buildMapIndexSheet(wb, payload)
  return wb
}

export function sarFloodReportExcelFilename(aoiName: string): string {
  const slug = aoiName.replace(/[^\w.-]+/g, '_').replace(/_+/g, '_').slice(0, 40) || 'AOI'
  return `SAR_Flood_Intelligence_${slug}.xlsx`
}

export async function generateSarFloodReportExcel(payload: SarFloodReportPayload): Promise<void> {
  const wb = await buildSarFloodReportWorkbook(payload)
  const buffer = await wb.xlsx.writeBuffer()
  const blob = new Blob([buffer], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = sarFloodReportExcelFilename(payload.aoiName)
  a.click()
  URL.revokeObjectURL(url)
}
