"""Attribute schema for automated EO enrichment of agricultural polygons."""

from __future__ import annotations

from typing import Any

from .rs_catalog import RS_MEAN_LAYER_IDS, all_rs_attribute_columns

_BASE_FIELDS: list[str] = [
    "Object_ID",
    "Object_Type",
    "Object_Name",
    "Boundary",
    "Centroid_Lat",
    "Centroid_Lon",
    "Estimated_Area_ha",
    "Agricultural_Status",
    "Activity_Status",
    "Land_Cover_Type",
    "Vegetation_Cover_Percent",
    "Crop_Type",
    "Crop_Confidence",
    "Cultivated_Area_ha",
    "Crop_Growth_Stage",
    "Estimated_Planting_Date",
    "Estimated_Harvest_Date",
    "Crop_Health",
]

_TAIL_FIELDS: list[str] = [
    "Water_Stress",
    "Soil_Moisture",
    "Actual_ET",
    "Crop_Water_Requirement",
    "Irrigation_Performance",
    "Estimated_Water_Use",
    "Water_Productivity",
    "Soil_Salinity",
    "Land_Degradation",
    "Land_Suitability",
    "Estimated_Yield",
    "Estimated_Total_Production",
    "Yield_Confidence",
    "Change_Previous_Period",
    "Newly_Cultivated",
    "Anomaly",
    "Field_Inspection_Priority",
    "Recommendation",
    "TimeSeries",
    "Satellite_Source",
    "Satellite_Name",
    "Scene_ID",
    "Acquisition_Date",
    "Cloud_Cover",
    "Cloud_Cover_Pct",
    "Spatial_Resolution",
    "Processing_Date",
    "NDVI_Min",
    "NDVI_Max",
    "NDVI_Mean",
    "NDMI_Mean",
    "EVI_Mean",
    "Pixel_Count",
    "Data_Quality_Score",
    "Analysis_Confidence",
    "Last_Update",
]

# Geometry/crop meta → all Layer-select index means → agronomic/meta tail
CORE_FIELDS: list[str] = list(dict.fromkeys([*_BASE_FIELDS, *all_rs_attribute_columns(), *_TAIL_FIELDS]))

FIELD_DEFAULTS: dict[str, Any] = {
    "Object_ID": None,
    "Object_Type": "Polygon",
    "Object_Name": "",
    "Boundary": "",
    "Centroid_Lat": None,
    "Centroid_Lon": None,
    "Estimated_Area_ha": None,
    "Agricultural_Status": "Unknown",
    "Activity_Status": "Unknown",
    "Land_Cover_Type": "Unknown",
    "Vegetation_Cover_Percent": None,
    "Crop_Type": "Unknown",
    "Crop_Confidence": None,
    "Cultivated_Area_ha": None,
    "Crop_Growth_Stage": "Unknown",
    "Estimated_Planting_Date": "",
    "Estimated_Harvest_Date": "",
    "Crop_Health": "Unknown",
    "Water_Stress": "Unknown",
    "Soil_Moisture": "Unknown",
    "Actual_ET": None,
    "Crop_Water_Requirement": None,
    "Irrigation_Performance": "Unknown",
    "Estimated_Water_Use": None,
    "Water_Productivity": None,
    "Soil_Salinity": "Unknown",
    "Land_Degradation": "Unknown",
    "Land_Suitability": "Unknown",
    "Estimated_Yield": None,
    "Estimated_Total_Production": None,
    "Yield_Confidence": None,
    "Change_Previous_Period": "No Change",
    "Newly_Cultivated": "Stable",
    "Anomaly": False,
    "Field_Inspection_Priority": "Low",
    "Recommendation": "",
    "TimeSeries": "Unknown",
    "Satellite_Source": "",
    "Satellite_Name": "Sentinel-2",
    "Scene_ID": "",
    "Acquisition_Date": "",
    "Cloud_Cover": None,
    "Cloud_Cover_Pct": None,
    "Spatial_Resolution": 10,
    "Processing_Date": "",
    "NDVI_Min": None,
    "NDVI_Max": None,
    "NDVI_Mean": None,
    "NDMI_Mean": None,
    "EVI_Mean": None,
    "Pixel_Count": None,
    "Data_Quality_Score": None,
    "Analysis_Confidence": None,
    "Last_Update": "",
}
for _lid in RS_MEAN_LAYER_IDS:
    FIELD_DEFAULTS.setdefault(_lid, None)

INDEX_NAMES: tuple[str, ...] = tuple(RS_MEAN_LAYER_IDS)

CROP_CLASSES = (
    "Rhodes Grass",
    "Wheat",
    "Maize",
    "Date Palm",
    "Alfalfa",
    "Vegetables",
    "Orchard",
    "Bare Soil",
    "Unknown",
)
