/**
 * Unique per-layer anchor palettes for AgroCloud composite indices.
 * Each layer owns a distinct color trajectory — no shared ramps between layers.
 * (NDVI, NDMI, NDWI, SAVI, CHAS, ΔCHAS are defined elsewhere and unchanged.)
 */

export type AgroLayerRampAnchor = { t: number; hex: number; label: string }

export type AgroLayerRampPalette = {
  valueMin: number
  valueMax: number
  anchors: AgroLayerRampAnchor[]
  classLabels: readonly string[]
  /** Legend subtitle — scientific reading of the ramp direction. */
  subtitle: string
}

function h(hex: string): number {
  return parseInt(hex.replace('#', ''), 16)
}

function anchors(...pairs: [number, string, string][]): AgroLayerRampAnchor[] {
  return pairs.map(([t, hex, label]) => ({ t, hex: h(hex), label }))
}

/** Linear RGB blend between two packed hex colors (amt 0 → a, 1 → b). */
function mixHex(a: number, b: number, amt: number): number {
  const t = Math.max(0, Math.min(1, amt))
  const ar = (a >> 16) & 0xff
  const ag = (a >> 8) & 0xff
  const ab = a & 0xff
  const br = (b >> 16) & 0xff
  const bg = (b >> 8) & 0xff
  const bb = b & 0xff
  const r = Math.round(ar + (br - ar) * t)
  const g = Math.round(ag + (bg - ag) * t)
  const bl = Math.round(ab + (bb - ab) * t)
  return ((r << 16) | (g << 8) | bl) >>> 0
}

function deltaLabels(shortName: string): readonly string[] {
  return [
    `Strong ${shortName} decline`,
    `Major ${shortName} decline`,
    `Moderate ${shortName} decline`,
    `Slight ${shortName} decline`,
    `Stable · low`,
    `Stable · neutral`,
    `Slight ${shortName} gain`,
    `Moderate ${shortName} gain`,
    `Major ${shortName} gain`,
    `Strong ${shortName} gain`,
  ]
}

/**
 * Unique delta palettes — smooth diverging ramp with 10 visibly distinct steps.
 *
 * The strong decline / gain colors anchor the dark, saturated extremes; toward
 * the stable center each side fades through progressively lighter mid-tones, so
 * every class is a clear, gradual step (dark → light → dark) rather than four
 * near-identical shades on each wing.
 */
function deltaPalette(
  shortName: string,
  decline: string,
  stable: string,
  gain: string,
  subtitle: string,
): AgroLayerRampPalette {
  const declineHex = h(decline)
  const stableHex = h(stable)
  const gainHex = h(gain)

  // Light tints near the neutral center (blend the strong hue toward stable).
  const declineLight = mixHex(declineHex, stableHex, 0.78)
  const gainLight = mixHex(gainHex, stableHex, 0.78)
  const declineMid = mixHex(declineHex, declineLight, 0.45)
  const gainMid = mixHex(gainHex, gainLight, 0.45)

  const rampAnchors: AgroLayerRampAnchor[] = [
    { t: 0, hex: declineHex, label: 'Strong decline' },
    { t: 0.22, hex: declineMid, label: 'Moderate decline' },
    { t: 0.44, hex: declineLight, label: 'Slight decline' },
    { t: 0.5, hex: stableHex, label: 'Stable' },
    { t: 0.56, hex: gainLight, label: 'Slight gain' },
    { t: 0.78, hex: gainMid, label: 'Moderate gain' },
    { t: 1, hex: gainHex, label: 'Strong gain' },
  ]

  return {
    valueMin: -0.4,
    valueMax: 0.4,
    anchors: rampAnchors,
    classLabels: deltaLabels(shortName),
    subtitle,
  }
}

/**
 * Static composite palettes — low value → high value semantics per index physics.
 */
export const AGRO_UNIQUE_LAYER_RAMP_PALETTES: Record<string, AgroLayerRampPalette> = {
  // 🌱 Vegetation Health Layer — 10-class reclass (−1 → 1), red (critical) → dark green (excellent)
  CVHI: {
    valueMin: -1,
    valueMax: 1,
    anchors: anchors(
      [0, '#b71c1c', 'Extreme stress'],
      [0.11, '#c62828', 'Severe'],
      [0.22, '#e53935', 'Very poor'],
      [0.33, '#ef5350', 'Poor'],
      [0.44, '#ff7043', 'Low health'],
      [0.55, '#ffb300', 'Moderate stress'],
      [0.66, '#9ccc65', 'Moderate health'],
      [0.77, '#66bb6a', 'Good'],
      [0.88, '#2e7d32', 'Very good'],
      [1, '#1b5e20', 'Excellent'],
    ),
    classLabels: [
      'Extreme Vegetation Stress',
      'Severe Degradation',
      'Very Poor Condition',
      'Poor Vegetation',
      'Low Vegetation Health',
      'Moderate Stress',
      'Moderate Vegetation Health',
      'Good Vegetation Condition',
      'Very Good Vegetation Health',
      'Excellent Vegetation Health',
    ],
    subtitle: '4-index composite mean · 🔴 critical stress → 🟢 excellent canopy health',
  },
  // 🌱 Vegetation Health Layer
  VHS: {
    valueMin: 0,
    valueMax: 1,
    anchors: anchors(
      [0, '#7f0000', 'Critical'],
      [0.33, '#d4a017', 'Weak'],
      [0.66, '#7cb342', 'Good'],
      [1, '#1b5e20', 'Excellent'],
    ),
    classLabels: [
      'Critical health',
      'Very poor',
      'Poor',
      'Below average',
      'Fair',
      'Moderate',
      'Good',
      'Very good',
      'Excellent',
      'Peak vigor',
    ],
    subtitle: 'Vegetation Health · crimson = poor · forest green = excellent',
  },
  VDI: {
    valueMin: 0,
    valueMax: 1,
    anchors: anchors(
      [0, '#2e7d32', 'Moist canopy'],
      [0.33, '#aed581', 'Hydrated'],
      [0.66, '#bcaaa4', 'Drying'],
      [1, '#4e342e', 'Very dry'],
    ),
    classLabels: [
      'Fully hydrated',
      'Well hydrated',
      'Moist',
      'Slightly dry',
      'Moderate dryness',
      'Dry canopy',
      'Very dry',
      'Severe dryness',
      'Critical dryness',
      'Desiccated',
    ],
    subtitle: 'Vegetation dryness · green = moist · brown = dry canopy',
  },
  CVI: {
    valueMin: 0,
    valueMax: 1,
    anchors: anchors(
      [0, '#4a148c', 'Low vigor'],
      [0.33, '#7e57c2', 'Sparse vigor'],
      [0.66, '#43a047', 'Moderate vigor'],
      [1, '#1b4332', 'Peak crop vigor'],
    ),
    classLabels: [
      'No vigor',
      'Very low',
      'Low',
      'Fair',
      'Moderate',
      'Good',
      'Strong',
      'Very strong',
      'Excellent',
      'Peak Crop Vigor',
    ],
    subtitle: 'Crop Vigor Index · purple = weak · deep green = vigorous canopy',
  },
  CSI: {
    valueMin: 0,
    valueMax: 1,
    anchors: anchors(
      [0, '#1b5e20', 'Low stress'],
      [0.33, '#fdd835', 'Watch'],
      [0.66, '#ef6c00', 'Stressed'],
      [1, '#b71c1c', 'Critical stress'],
    ),
    classLabels: [
      'Minimal stress',
      'Low stress',
      'Mild stress',
      'Moderate stress',
      'Elevated',
      'High stress',
      'Very high',
      'Severe',
      'Critical',
      'Collapse risk',
    ],
    subtitle: 'Crop stress · green = healthy · red = severe stress',
  },
  WST: {
    valueMin: -1,
    valueMax: 1,
    anchors: anchors(
      [0, '#0d47a1', 'Well watered'],
      [0.33, '#4fc3f7', 'Adequate'],
      [0.66, '#ffb74d', 'Water limited'],
      [1, '#e65100', 'Severe water stress'],
    ),
    classLabels: [
      'No water stress',
      'Very low stress',
      'Low stress',
      'Mild stress',
      'Moderate',
      'Elevated stress',
      'High stress',
      'Very high',
      'Severe',
      'Extreme water stress',
    ],
    subtitle: 'Water stress · blue = adequate moisture · orange = stressed',
  },

  // 💧 Water & Moisture Layer
  DRI: {
    valueMin: 0,
    valueMax: 1,
    anchors: anchors(
      [0, '#0277bd', 'Low drought risk'],
      [0.33, '#81d4fa', 'Mild risk'],
      [0.66, '#ffcc80', 'Moderate drought'],
      [1, '#bf360c', 'Extreme drought'],
    ),
    classLabels: [
      'Minimal drought',
      'Low risk',
      'Mild risk',
      'Moderate risk',
      'Elevated',
      'High drought',
      'Very high',
      'Severe',
      'Extreme',
      'Catastrophic drought',
    ],
    subtitle: 'Drought risk · sky blue = wet · rust = extreme drought',
  },
  VMI: {
    valueMin: -0.5,
    valueMax: 0.5,
    anchors: anchors(
      [0, '#004d40', 'Very dry canopy'],
      [0.33, '#00897b', 'Dry'],
      [0.66, '#4db6ac', 'Moist'],
      [1, '#b2dfdb', 'Saturated canopy'],
    ),
    classLabels: [
      'Extremely dry',
      'Very dry',
      'Dry',
      'Slightly dry',
      'Neutral',
      'Slightly moist',
      'Moist',
      'Wet canopy',
      'Very wet',
      'Saturated',
    ],
    subtitle: 'Canopy moisture · deep teal = dry · pale aqua = wet foliage',
  },
  SMI: {
    valueMin: -0.5,
    valueMax: 0.5,
    anchors: anchors(
      [0, '#5d4037', 'Dry soil'],
      [0.33, '#a1887f', 'Low moisture'],
      [0.66, '#26c6da', 'Moist soil'],
      [1, '#006064', 'Saturated soil'],
    ),
    classLabels: [
      'Bone dry soil',
      'Very dry',
      'Dry',
      'Slightly dry',
      'Neutral',
      'Slightly moist',
      'Moist soil',
      'Wet soil',
      'Very wet',
      'Waterlogged soil',
    ],
    subtitle: 'Soil moisture · clay brown = dry · cyan = wet soil profile',
  },
  OIR: {
    valueMin: -1,
    valueMax: 1,
    anchors: anchors(
      [0, '#33691e', 'Balanced'],
      [0.33, '#fff176', 'Watch'],
      [0.66, '#29b6f6', 'Over-wet'],
      [1, '#0d47a1', 'Flood / excess irrigation'],
    ),
    classLabels: [
      'Optimal balance',
      'Normal',
      'Slight excess watch',
      'Moderate excess',
      'Elevated water',
      'High excess',
      'Over-irrigation',
      'Severe excess',
      'Very severe',
      'Critical over-irrigation',
    ],
    subtitle: 'Over-irrigation · green = balanced · navy = excess water',
  },
  WDSI: {
    valueMin: -0.5,
    valueMax: 0.65,
    anchors: anchors(
      [0, '#4e342e', 'Severe drought'],
      [0.25, '#bf360c', 'High drought'],
      [0.5, '#ffb300', 'Moderate drought'],
      [0.75, '#81c784', 'Near normal'],
      [1, '#0277bd', 'Wet / no drought'],
    ),
    classLabels: [
      'Extreme drought situation',
      'Severe drought',
      'High drought',
      'Elevated drought',
      'Moderate drought',
      'Mild drought / watch',
      'Near normal',
      'Adequate moisture',
      'Wet conditions',
      'No drought / surplus water',
    ],
    subtitle:
      'WDSI · 0.40·NDMI + 0.35·NDWI + 0.15·NDVI + 0.10·SAVI · brown = drought · blue = wet',
  },

  // 🚜 Irrigation & Field Management
  IEI: {
    valueMin: -1,
    valueMax: 2,
    anchors: anchors(
      [0, '#c62828', 'Inefficient'],
      [0.33, '#ffa726', 'Sub-optimal'],
      [0.66, '#66bb6a', 'Efficient'],
      [1, '#1565c0', 'Highly efficient'],
    ),
    classLabels: [
      'Critical inefficiency',
      'Poor efficiency',
      'Below target',
      'Fair',
      'Moderate',
      'Good efficiency',
      'Very good',
      'Excellent',
      'Optimal',
      'Peak efficiency',
    ],
    subtitle: 'Irrigation efficiency · red = waste · blue = optimal delivery',
  },
  UII: {
    valueMin: -1,
    valueMax: 1,
    anchors: anchors(
      [0, '#1b5e20', 'Well irrigated'],
      [0.33, '#689f38', 'Adequate'],
      [0.66, '#fdd835', 'Under-irrigated'],
      [1, '#f57f17', 'Severe deficit'],
    ),
    classLabels: [
      'No deficit',
      'Minimal deficit',
      'Low deficit',
      'Mild deficit',
      'Moderate',
      'Elevated deficit',
      'High deficit',
      'Very high',
      'Severe under-irrigation',
      'Critical deficit',
    ],
    subtitle: 'Under-irrigation · dark green = sufficient · amber = deficit',
  },
  FPR: {
    valueMin: 0,
    valueMax: 2,
    anchors: anchors(
      [0, '#2e7d32', 'High performance'],
      [0.33, '#ffeb3b', 'Average'],
      [0.66, '#ff7043', 'Below target'],
      [1, '#d84315', 'Poor performance'],
    ),
    classLabels: [
      'Peak performance',
      'Excellent',
      'Good',
      'Fair',
      'Moderate',
      'Below average',
      'Poor',
      'Very poor',
      'Critical',
      'Field failure',
    ],
    subtitle: 'Field performance · green = high yield potential · red = poor',
  },
  CPI: {
    valueMin: 0,
    valueMax: 1,
    anchors: anchors(
      [0, '#fff8e1', 'Low production'],
      [0.33, '#c5e1a5', 'Moderate'],
      [0.66, '#558b2f', 'Good'],
      [1, '#1b5e20', 'High production'],
    ),
    classLabels: [
      'Minimal production',
      'Very low',
      'Low',
      'Below average',
      'Moderate',
      'Fair production',
      'Good',
      'Very good',
      'High',
      'Peak production',
    ],
    subtitle: 'Crop production · straw = weak · deep green = high output',
  },
  ISS: {
    valueMin: -0.5,
    valueMax: 0.65,
    anchors: anchors(
      [0, '#b71c1c', 'Severe irrigation stress'],
      [0.28, '#ef6c00', 'High stress'],
      [0.52, '#fdd835', 'Moderate / watch'],
      [0.76, '#26a69a', 'Adequate moisture'],
      [1, '#006064', 'Well supplied'],
    ),
    classLabels: [
      'Critical irrigation stress',
      'Severe stress',
      'High stress',
      'Elevated stress',
      'Moderate stress',
      'Watch / borderline',
      'Adequately supplied',
      'Good moisture',
      'Well irrigated',
      'Optimal water status',
    ],
    subtitle:
      'ISS · 0.40·NDMI + 0.30·NDWI + 0.20·NDVI + 0.10·SAVI · red = stress · teal = well watered',
  },
  WAPI: {
    valueMin: 0,
    valueMax: 1,
    anchors: anchors(
      [0, '#5c6bc0', 'Class 1 · Normal'],
      [0.22, '#26a69a', 'Class 3 · Low Stress'],
      [0.44, '#fdd835', 'Class 5 · Moderate'],
      [0.66, '#ef6c00', 'Class 7 · High Stress'],
      [0.88, '#e91e63', 'Class 9 · Critical'],
      [1, '#ad1457', 'Class 10 · Extreme Critical'],
    ),
    classLabels: [
      'Class 1 · Normal · 0.00–0.09',
      'Class 2 · Healthy · 0.10–0.19',
      'Class 3 · Low Stress · 0.20–0.29',
      'Class 4 · Low Moderate · 0.30–0.39',
      'Class 5 · Moderate · 0.40–0.49',
      'Class 6 · Moderate High · 0.50–0.59',
      'Class 7 · High Stress · 0.60–0.69',
      'Class 8 · Very High Stress · 0.70–0.79',
      'Class 9 · Critical · 0.80–0.89',
      'Class 10 · Extreme Critical · 0.90–1.00',
    ],
    subtitle:
      'WAPI 10-class · 0.40·WDSI + 0.20·ΔWDSI + 0.20·(1−NDMI) + 0.10·ETstress + 0.10 · blue = Normal · magenta = Extreme Critical',
  },

  // 🌾 Growth & Stability
  GPI: {
    valueMin: 0,
    valueMax: 1,
    anchors: anchors(
      [0, '#e65100', 'Stagnant'],
      [0.33, '#ffb300', 'Slow growth'],
      [0.66, '#7cb342', 'Active growth'],
      [1, '#33691e', 'Peak growth'],
    ),
    classLabels: [
      'No growth',
      'Very slow',
      'Slow',
      'Below average',
      'Moderate growth',
      'Fair growth',
      'Good growth',
      'Strong growth',
      'Very strong',
      'Peak growth rate',
    ],
    subtitle: 'Growth performance · orange = lag · lime green = active growth',
  },
  CSI2: {
    valueMin: 0,
    valueMax: 1,
    anchors: anchors(
      [0, '#37474f', 'Unstable canopy'],
      [0.33, '#78909c', 'Variable'],
      [0.66, '#aed581', 'Stable'],
      [1, '#33691e', 'Highly stable'],
    ),
    classLabels: [
      'Highly unstable',
      'Unstable',
      'Variable',
      'Moderately variable',
      'Fair stability',
      'Stable',
      'Good stability',
      'Very stable',
      'Excellent stability',
      'Locked stable canopy',
    ],
    subtitle: 'Canopy stability · slate gray = unstable · green = stable cover',
  },
  CRI: {
    valueMin: 0,
    valueMax: 1.5,
    anchors: anchors(
      [0, '#311b92', 'Low resilience'],
      [0.33, '#5c6bc0', 'Fragile'],
      [0.66, '#81c784', 'Resilient'],
      [1, '#2e7d32', 'Highly resilient'],
    ),
    classLabels: [
      'Critical fragility',
      'Very low resilience',
      'Low',
      'Below average',
      'Moderate',
      'Fair resilience',
      'Good',
      'Strong',
      'Very resilient',
      'Maximum resilience',
    ],
    subtitle: 'Crop resilience · indigo = fragile · green = stress-tolerant',
  },
  VDG: {
    valueMin: 0,
    valueMax: 1,
    anchors: anchors(
      [0, '#1b5e20', 'Stable / no decline'],
      [0.33, '#ffca28', 'Early decline'],
      [0.66, '#ff5722', 'Active decline'],
      [1, '#3e2723', 'Severe decline gradient'],
    ),
    classLabels: [
      'No decline',
      'Minimal decline',
      'Slight decline',
      'Moderate decline',
      'Elevated decline',
      'High decline',
      'Very high',
      'Severe',
      'Critical decline',
      'Collapse gradient',
    ],
    subtitle: 'Vegetation decline · green = stable · charcoal = steep loss',
  },

  // ⚠️ Risk & Composite
  ARI: {
    valueMin: 0,
    valueMax: 1,
    anchors: anchors(
      [0, '#00c853', 'Low agro risk'],
      [0.33, '#ffeb3b', 'Watch'],
      [0.66, '#ff5722', 'High risk'],
      [1, '#d50000', 'Critical agro risk'],
    ),
    classLabels: [
      'Minimal risk',
      'Low risk',
      'Mild risk',
      'Moderate',
      'Elevated',
      'High risk',
      'Very high',
      'Severe',
      'Critical',
      'Extreme agro risk',
    ],
    subtitle: 'Agro risk · bright green = safe · red = critical composite risk',
  },
  CHS: {
    valueMin: 0,
    valueMax: 1,
    anchors: anchors(
      [0, '#880e4f', 'Poor crop health'],
      [0.33, '#f06292', 'Fair'],
      [0.66, '#81c784', 'Good'],
      [1, '#004d40', 'Excellent crop health'],
    ),
    classLabels: [
      'Critical health',
      'Very poor',
      'Poor',
      'Below average',
      'Moderate',
      'Fair',
      'Good',
      'Very good',
      'Excellent',
      'Peak Crop Health',
    ],
    subtitle: 'Crop Health Score · magenta = poor · teal = excellent',
  },
  CPS: {
    valueMin: 0,
    valueMax: 2,
    anchors: anchors(
      [0, '#e8f5e9', 'Low pressure'],
      [0.33, '#fff59d', 'Moderate pressure'],
      [0.66, '#ff7043', 'High pressure'],
      [1, '#4a148c', 'Extreme crop pressure'],
    ),
    classLabels: [
      'Minimal pressure',
      'Low',
      'Mild',
      'Moderate',
      'Elevated',
      'High pressure',
      'Very high',
      'Severe',
      'Critical pressure',
      'Extreme pressure',
    ],
    subtitle: 'Crop pressure · mint = low stress load · violet = extreme pressure',
  },

  // 📅 Crop Phenology & Calendar
  PRI: {
    valueMin: 0,
    valueMax: 1,
    anchors: anchors(
      [0, '#efebe9', 'Not ready'],
      [0.35, '#ffb74d', 'Approaching'],
      [0.45, '#66bb6a', 'Planting ready'],
      [1, '#1b5e20', 'Peak readiness'],
    ),
    classLabels: [
      'Not ready',
      'Very early',
      'Early',
      'Approaching',
      'Near ready',
      'Planting ready',
      'Good window',
      'Strong window',
      'Excellent',
      'Peak planting readiness',
    ],
    subtitle: 'Planting Readiness Index · beige = wait · green = plant',
  },
  CGI: {
    valueMin: 0,
    valueMax: 1,
    anchors: anchors(
      [0, '#4a148c', 'No growth'],
      [0.33, '#7e57c2', 'Establishing'],
      [0.66, '#43a047', 'Active growth'],
      [1, '#1b5e20', 'Peak growth'],
    ),
    classLabels: [
      'No growth',
      'Very slow',
      'Slow',
      'Establishing',
      'Moderate',
      'Good growth',
      'Strong growth',
      'Very strong',
      'Excellent',
      'Peak Crop Growth',
    ],
    subtitle: 'Crop Growth Index · purple = stagnant · green = vigorous growth',
  },
  CMI: {
    valueMin: 0,
    valueMax: 1,
    anchors: anchors(
      [0, '#e3f2fd', 'Immature'],
      [0.33, '#81d4fa', 'Developing'],
      [0.66, '#ffb300', 'Maturing'],
      [1, '#e65100', 'Mature'],
    ),
    classLabels: [
      'Immature',
      'Very early',
      'Early',
      'Developing',
      'Mid season',
      'Late vegetative',
      'Early maturity',
      'Maturing',
      'Near mature',
      'Fully mature',
    ],
    subtitle: 'Crop Maturity Index · blue = young · orange = mature',
  },
  HRI: {
    valueMin: 0,
    valueMax: 1,
    anchors: anchors(
      [0, '#1b5e20', 'Not harvest-ready'],
      [0.5, '#fff59d', 'Approaching harvest'],
      [0.7, '#fb8c00', 'Harvest ready'],
      [1, '#bf360c', 'Peak harvest readiness'],
    ),
    classLabels: [
      'Not ready',
      'Very early',
      'Early',
      'Approaching',
      'Near ready',
      'Almost ready',
      'Harvest ready',
      'Good window',
      'Strong window',
      'Peak harvest readiness',
    ],
    subtitle: 'Harvest Readiness Index · green = wait · orange = harvest',
  },
  VRI: {
    valueMin: 0,
    valueMax: 1,
    anchors: anchors(
      [0, '#b71c1c', 'Season low'],
      [0.33, '#ffcc80', 'Recovering'],
      [0.66, '#81c784', 'Strong recovery'],
      [1, '#1b5e20', 'Season peak'],
    ),
    classLabels: [
      'Season minimum',
      'Very low recovery',
      'Low',
      'Fair',
      'Moderate',
      'Recovering',
      'Good recovery',
      'Strong',
      'Near peak',
      'Season peak NDVI',
    ],
    subtitle: 'Vegetation Recovery Index · red = low · green = recovered vs season range',
  },
  CCI: {
    valueMin: 0,
    valueMax: 1,
    anchors: anchors(
      [0, '#37474f', 'Low confidence'],
      [0.33, '#90a4ae', 'Uncertain'],
      [0.66, '#42a5f5', 'Reliable'],
      [1, '#0d47a1', 'High confidence'],
    ),
    classLabels: [
      'Very low confidence',
      'Low',
      'Limited',
      'Uncertain',
      'Moderate',
      'Fair',
      'Reliable',
      'High',
      'Very high',
      'Peak calendar confidence',
    ],
    subtitle: 'Crop Calendar Confidence · gray = sparse/noisy · blue = stable dense observations',
  },
  EPD: {
    valueMin: 0,
    valueMax: 1,
    anchors: anchors(
      [0, '#efebe9', 'Before planting window'],
      [0.45, '#66bb6a', 'Planting signal'],
      [1, '#1b5e20', 'Post planting-ready'],
    ),
    classLabels: [
      'Before window',
      'Very early',
      'Early',
      'Approaching',
      'Near signal',
      'Planting signal',
      'Confirmed',
      'Strong',
      'Very strong',
      'Peak planting signal',
    ],
    subtitle: 'Estimated Planting Date readiness (PRI surface on map)',
  },
  EHD: {
    valueMin: 0,
    valueMax: 1,
    anchors: anchors(
      [0, '#1b5e20', 'Before harvest window'],
      [0.7, '#fb8c00', 'Harvest signal'],
      [1, '#bf360c', 'Post harvest-ready'],
    ),
    classLabels: [
      'Before window',
      'Very early',
      'Early',
      'Approaching',
      'Near signal',
      'Near ready',
      'Harvest signal',
      'Confirmed',
      'Strong',
      'Peak harvest signal',
    ],
    subtitle: 'Estimated Harvest Date readiness (HRI surface on map)',
  },

  // 🧂 Soil & Salinity Layer — Low → High salinity (green = non-saline → maroon = extreme)
  SAL_NDSI: {
    valueMin: -0.6,
    valueMax: 0.4,
    anchors: anchors(
      [0, '#1b5e20', 'Non-saline'],
      [0.33, '#fdd835', 'Slight salinity'],
      [0.66, '#ef6c00', 'High salinity'],
      [1, '#7f0000', 'Extreme salinity'],
    ),
    classLabels: [
      'Non-saline',
      'Very low salinity',
      'Low salinity',
      'Slight salinity',
      'Moderate salinity',
      'Moderately high',
      'High salinity',
      'Very high salinity',
      'Severe salinity',
      'Extreme salinity',
    ],
    subtitle: 'Salinity NDSI (B11−B8)/(B11+B8) · Low → High · 🟢 non-saline → 🔴 extreme salinity',
  },
  SI: {
    valueMin: 0,
    valueMax: 0.4,
    anchors: anchors(
      [0, '#00695c', 'Non-saline'],
      [0.33, '#cddc39', 'Slight salinity'],
      [0.66, '#f4511e', 'High salinity'],
      [1, '#880e4f', 'Extreme salinity'],
    ),
    classLabels: [
      'Non-saline',
      'Very low salinity',
      'Low salinity',
      'Slight salinity',
      'Moderate salinity',
      'Moderately high',
      'High salinity',
      'Very high salinity',
      'Severe salinity',
      'Extreme salinity',
    ],
    subtitle: 'SI √(B3·B4) · Low → High · 🟢 dark soil → 🔴 bright saline crust',
  },
  SSI: {
    valueMin: -0.4,
    valueMax: 0.8,
    anchors: anchors(
      [0, '#0d47a1', 'Non-saline'],
      [0.33, '#4dd0e1', 'Slight salinity'],
      [0.66, '#ffa726', 'High salinity'],
      [1, '#3e2723', 'Extreme salinity'],
    ),
    classLabels: [
      'Non-saline',
      'Very low salinity',
      'Low salinity',
      'Slight salinity',
      'Moderate salinity',
      'Moderately high',
      'High salinity',
      'Very high salinity',
      'Severe salinity',
      'Extreme salinity',
    ],
    subtitle: 'SSI (Salinity NDSI + SI) · Low → High · combined normalized + brightness salinity',
  },

  // 🪙 Gold Exploration Indices — low → high mineral / alteration / prospectivity
  IOI: {
    valueMin: 0.5,
    valueMax: 2.5,
    anchors: anchors(
      [0, '#0d1b2a', 'Background'],
      [0.22, '#415a77', 'Weak iron oxide'],
      [0.44, '#9a031e', 'Moderate iron oxide'],
      [0.66, '#e36414', 'Strong iron oxide'],
      [1, '#ffba08', 'Extreme iron oxide'],
    ),
    classLabels: [
      'Background / negligible Fe-oxide',
      'Very weak iron oxide',
      'Weak iron oxide',
      'Low–moderate iron oxide',
      'Moderate iron oxide',
      'Elevated iron oxide',
      'Strong iron oxide',
      'Very strong iron oxide',
      'Intense Fe-oxide alteration',
      'Extreme Fe-oxide signature',
    ],
    subtitle: 'Iron Oxide Index (B04/B02) · 10-class · navy → crimson → gold Fe-oxide enrichment',
  },
  CLAY_MI: {
    valueMin: 0.7,
    valueMax: 1.5,
    anchors: anchors(
      [0, '#134e4a', 'Background clay'],
      [0.25, '#5eead4', 'Weak clay'],
      [0.5, '#fef3c7', 'Moderate clay'],
      [0.75, '#c026d3', 'Strong clay'],
      [1, '#4a044e', 'Extreme clay'],
    ),
    classLabels: [
      'Background / negligible clay',
      'Very weak clay minerals',
      'Weak clay minerals',
      'Low–moderate clay',
      'Moderate clay alteration',
      'Elevated clay minerals',
      'Strong clay alteration',
      'Very strong clay',
      'Intense clay alteration',
      'Extreme clay mineral signature',
    ],
    subtitle: 'Clay Mineral Index (B11/B12) · 10-class · teal → cream → magenta clay alteration',
  },
  FMI: {
    valueMin: 0.4,
    valueMax: 2.0,
    anchors: anchors(
      [0, '#14532d', 'Background ferrous'],
      [0.25, '#84cc16', 'Weak ferrous'],
      [0.5, '#facc15', 'Moderate ferrous'],
      [0.75, '#b45309', 'Strong ferrous'],
      [1, '#7c2d12', 'Extreme ferrous'],
    ),
    classLabels: [
      'Background / negligible ferrous',
      'Very weak ferrous minerals',
      'Weak ferrous minerals',
      'Low–moderate ferrous',
      'Moderate ferrous minerals',
      'Elevated ferrous minerals',
      'Strong ferrous minerals',
      'Very strong ferrous',
      'Intense ferrous signature',
      'Extreme ferrous mineral enrichment',
    ],
    subtitle: 'Ferrous Mineral Index (B11/B08) · 10-class · green → yellow → rust ferrous enrichment',
  },
  NDAI: {
    valueMin: -0.3,
    valueMax: 0.5,
    anchors: anchors(
      [0, '#1e3a8a', 'Low alteration'],
      [0.25, '#93c5fd', 'Weak alteration'],
      [0.5, '#f8fafc', 'Neutral'],
      [0.75, '#f87171', 'Strong alteration'],
      [1, '#7f1d1d', 'Extreme alteration'],
    ),
    classLabels: [
      'Very low alteration',
      'Low alteration',
      'Weak alteration',
      'Slight alteration',
      'Neutral / background',
      'Moderate alteration',
      'Elevated alteration',
      'Strong alteration',
      'Very strong alteration',
      'Extreme hydrothermal alteration',
    ],
    subtitle: 'NDAI (B11−B12)/(B11+B12) · 10-class · blue → white → red alteration contrast',
  },
  BSI: {
    valueMin: -0.5,
    valueMax: 0.5,
    anchors: anchors(
      [0, '#166534', 'Vegetated / low bare'],
      [0.25, '#a3e635', 'Sparse cover'],
      [0.5, '#fde047', 'Mixed bare soil'],
      [0.75, '#d97706', 'Exposed soil'],
      [1, '#78350f', 'Extreme bare soil'],
    ),
    classLabels: [
      'Dense vegetation / minimal bare soil',
      'Mostly vegetated',
      'Low bare soil',
      'Sparse cover',
      'Mixed soil–vegetation',
      'Moderate bare soil',
      'Elevated bare soil',
      'Strongly exposed soil',
      'Very high bare soil',
      'Extreme bare soil / rock exposure',
    ],
    subtitle: 'Bare Soil Index · 10-class · green canopy → yellow mix → brown bare earth',
  },
  REAI: {
    valueMin: 0.7,
    valueMax: 1.4,
    anchors: anchors(
      [0, '#312e81', 'Background red-edge'],
      [0.25, '#6366f1', 'Weak red-edge'],
      [0.5, '#22d3ee', 'Moderate red-edge'],
      [0.75, '#fbbf24', 'Strong red-edge'],
      [1, '#b45309', 'Extreme red-edge'],
    ),
    classLabels: [
      'Background red-edge response',
      'Very weak red-edge alteration',
      'Weak red-edge alteration',
      'Low–moderate red-edge',
      'Moderate red-edge alteration',
      'Elevated red-edge response',
      'Strong red-edge alteration',
      'Very strong red-edge',
      'Intense red-edge alteration',
      'Extreme red-edge alteration',
    ],
    subtitle: 'Red Edge Alteration Index (B06/B05) · 10-class · indigo → cyan → amber alteration',
  },
  GEI: {
    valueMin: 0.4,
    valueMax: 2.0,
    anchors: anchors(
      [0, '#0f172a', 'Low prospectivity'],
      [0.22, '#0e7490', 'Weak composite'],
      [0.44, '#ca8a04', 'Moderate prospectivity'],
      [0.66, '#ea580c', 'High prospectivity'],
      [1, '#9f1239', 'Extreme prospectivity'],
    ),
    classLabels: [
      'Negligible gold-prospectivity composite',
      'Very low prospectivity',
      'Low prospectivity',
      'Low–moderate prospectivity',
      'Moderate prospectivity',
      'Elevated prospectivity',
      'High prospectivity',
      'Very high prospectivity',
      'Intense composite signature',
      'Extreme gold-exploration composite',
    ],
    subtitle:
      'GEI 0.35·IOI + 0.30·CMI + 0.20·FMI + 0.15·BSI · 10-class · navy → gold → crimson prospectivity',
  },
  GCI: {
    valueMin: 0.3,
    valueMax: 1.8,
    anchors: anchors(
      [0, '#1a237e', 'No Gold Indication'],
      [0.22, '#0277bd', 'Very Weak Indication'],
      [0.44, '#f9a825', 'Moderate-Low Potential'],
      [0.66, '#ef6c00', 'High Alteration Zone'],
      [1, '#b71c1c', 'Extreme Gold Target'],
    ),
    classLabels: [
      'No Gold Indication',
      'Very Weak Indication',
      'Weak Indication',
      'Low Potential',
      'Moderate-Low Potential',
      'Moderate Potential',
      'High Alteration Zone',
      'High Gold Potential',
      'Very High Gold Potential',
      'Extreme Gold Target',
    ],
    subtitle:
      'GCI 0.30·IOI + 0.25·CMI + 0.20·FMI + 0.15·NDAI + 0.10·BSI · Class 1 No Gold → Class 10 Extreme Gold Target',
  },
  EGCI: {
    valueMin: 0,
    valueMax: 1,
    anchors: anchors(
      [0, '#fff8e1', 'Background'],
      [0.11, '#ffe082', 'Very Low'],
      [0.22, '#ffd54f', 'Low Au Indication'],
      [0.33, '#ffb300', 'Weak Mineralization'],
      [0.44, '#fb8c00', 'Moderate-Low Mineralization'],
      [0.55, '#f4511e', 'Moderate Mineralization'],
      [0.66, '#d81b60', 'Strong Alteration / Possible Au Zone'],
      [0.77, '#9c27b0', 'High Mineralized Zone'],
      [0.88, '#6a1b9a', 'High Au Concentration Target'],
      [1, '#4a148c', 'Very High Au Concentration Target'],
    ),
    classLabels: [
      'Background',
      'Very Low',
      'Low Au Indication',
      'Weak Mineralization',
      'Moderate-Low Mineralization',
      'Moderate Mineralization',
      'Strong Alteration / Possible Au Zone',
      'High Mineralized Zone',
      'High Au Concentration Target',
      'Very High Au Concentration Target',
    ],
    subtitle:
      'EGCI 0.30·IOIN + 0.25·CMIN + 0.20·FMIN + 0.15·NDAIN + 0.10·BSIN · luminous gold → amber → magenta → violet Au ramp',
  },

  // Δ layers — each with a unique stable-center hue
  DCVHI: deltaPalette('CVHI', '#b71c1c', '#fff176', '#1b5e20', 'ΔCVHI · composite health decline → recovery'),
  DVHS: deltaPalette('VHS', '#8b0000', '#fffde7', '#1b4332', 'ΔVHS · unique crimson→cream→forest change ramp'),
  DVDI: deltaPalette('VDI', '#4e342e', '#eceff1', '#2e7d32', 'ΔVDI · brown dry decline · gray stable · green rehydration'),
  DCVI: deltaPalette('CVI', '#4a148c', '#e1bee7', '#1b4332', 'ΔCVI · purple loss · lilac stable · green gain'),
  DCSI: deltaPalette('CSI', '#b71c1c', '#fff9c4', '#1b5e20', 'ΔCSI · stress easing vs intensification'),
  DWST: deltaPalette('WST', '#e65100', '#cfd8dc', '#0d47a1', 'ΔWST · orange stress rise · blue relief'),
  DDRI: deltaPalette('DRI', '#bf360c', '#ffe0b2', '#0277bd', 'ΔDRI · drought worsening · wetting recovery'),
  DVMI: deltaPalette('VMI', '#004d40', '#b2dfdb', '#80cbc4', 'ΔVMI · canopy moisture loss · teal recovery'),
  DSMI: deltaPalette('SMI', '#5d4037', '#d7ccc8', '#006064', 'ΔSMI · soil drying · cyan rewetting'),
  DOIR: deltaPalette('OIR', '#0d47a1', '#fff59d', '#33691e', 'ΔOIR · excess water rise · green normalization'),
  DWDSI: deltaPalette('WDSI', '#4e342e', '#fff3e0', '#0277bd', 'ΔWDSI · drought worsening · wetting recovery'),
  DIEI: deltaPalette('IEI', '#c62828', '#e3f2fd', '#1565c0', 'ΔIEI · efficiency drop · blue improvement'),
  DUII: deltaPalette('UII', '#f57f17', '#f0f4c3', '#1b5e20', 'ΔUII · deficit increase · irrigation recovery'),
  DFPR: deltaPalette('FPR', '#d84315', '#fff9c4', '#2e7d32', 'ΔFPR · performance drop · yield recovery'),
  DCPI: deltaPalette('CPI', '#fff8e1', '#c5e1a5', '#1b5e20', 'ΔCPI · production decline · output gain'),
  DISS: deltaPalette('ISS', '#b71c1c', '#fff8e1', '#006064', 'ΔISS · irrigation stress rise · moisture recovery'),
  DWAPI: deltaPalette('WAPI', '#1565c0', '#fffde7', '#c62828', 'ΔWAPI · priority easing · priority surge'),
  DGPI: deltaPalette('GPI', '#e65100', '#fff3e0', '#33691e', 'ΔGPI · growth slowdown · acceleration'),
  DCSI2: deltaPalette('CSI2', '#37474f', '#cfd8dc', '#33691e', 'ΔCSI2 · canopy destabilization · restabilization'),
  DCRI: deltaPalette('CRI', '#311b92', '#c5cae9', '#2e7d32', 'ΔCRI · resilience loss · recovery'),
  DVDG: deltaPalette('VDG', '#3e2723', '#ffecb3', '#1b5e20', 'ΔVDG · decline acceleration · vegetation recovery'),
  DARI: deltaPalette('ARI', '#d50000', '#fffde7', '#00c853', 'ΔARI · rising composite risk · risk reduction'),
  DCHS: deltaPalette('CHS', '#880e4f', '#f8bbd0', '#004d40', 'ΔCHS · crop health drop · recovery'),
  DCPS: deltaPalette('CPS', '#4a148c', '#e1bee7', '#e8f5e9', 'ΔCPS · pressure increase · relief'),
  DPRI: deltaPalette('PRI', '#e65100', '#fff3e0', '#1b5e20', 'ΔPRI · planting readiness drop · rise'),
  DCGI: deltaPalette('CGI', '#4a148c', '#e1bee7', '#2e7d32', 'ΔCGI · growth slowdown · acceleration'),
  DCMI: deltaPalette('CMI', '#1a237e', '#c5cae9', '#f9a825', 'ΔCMI · maturity retreat · advance'),
  DHRI: deltaPalette('HRI', '#1b5e20', '#fff9c4', '#e65100', 'ΔHRI · harvest readiness drop · rise'),
  DVRI: deltaPalette('VRI', '#b71c1c', '#eceff1', '#1b5e20', 'ΔVRI · recovery loss · canopy recovery'),
  DCCI: deltaPalette('CCI', '#37474f', '#cfd8dc', '#1565c0', 'ΔCCI · calendar confidence drop · rise'),
  DEPD: deltaPalette('EPD', '#e65100', '#fff3e0', '#2e7d32', 'ΔEPD · planting readiness change'),
  DEHD: deltaPalette('EHD', '#1b5e20', '#fffde7', '#ef6c00', 'ΔEHD · harvest readiness change'),
  DSAL_NDSI: deltaPalette('SAL_NDSI', '#1b5e20', '#fff9c4', '#7f0000', 'ΔSalinity NDSI · salinity easing · salinity build-up'),
  DSI: deltaPalette('SI', '#00695c', '#e0f2f1', '#6a1b9a', 'ΔSI · brightness/salinity decline · increase'),
  DSSI: deltaPalette('SSI', '#0d47a1', '#eceff1', '#3e2723', 'ΔSSI · combined salinity decline · increase'),
}
