import type { AppLanguage } from './i18n'

export const pwaInstallText = {
  en: {
    title: 'Install AgroCloud',
    subtitle: 'Add to your home screen for a fast, full-screen app experience.',
    featureFast: 'Faster loads on weak networks',
    featureFullscreen: 'Standalone full-screen mode',
    featureSame: 'Same AgroCloud features as the website',
    install: 'Install app',
    installing: 'Installing…',
    notNow: 'Not now',
    fabLabel: 'Install app',
    iosStep1: 'Tap Share in the Safari toolbar',
    iosStep2: 'Scroll and choose Add to Home Screen',
    iosStep3: 'Tap Add, then open AgroCloud from your home screen',
    ipadStep1: 'In Safari, tap Share (square with arrow) in the top toolbar',
    ipadStep2: 'Tap Add to Home Screen in the share sheet',
    ipadStep3: 'Confirm the name AgroCloud, tap Add, then launch from the home screen',
    iosSafariTitle: 'Open in Safari to install',
    iosSafariSubtitle: 'On iPhone and iPad, Add to Home Screen works only in Apple Safari.',
    iosSafariStep1: 'Copy this page link',
    iosSafariStep2: 'Open Safari and paste the link in the address bar',
    iosSafariStep3: 'Tap Share → Add to Home Screen',
    copyLink: 'Copy link',
    copied: 'Copied',
    androidStep1: 'Tap the menu (⋮) in Chrome',
    androidStep2: 'Choose Install app or Add to Home screen',
    androidStep3: 'Open AgroCloud from your home screen — it runs like a native app',
  },
  ar: {
    title: 'تثبيت AgroCloud',
    subtitle: 'أضِف التطبيق إلى الشاشة الرئيسية لتجربة سريعة بملء الشاشة.',
    featureFast: 'تحميل أسرع على الشبكات الضعيفة',
    featureFullscreen: 'وضع ملء الشاشة بدون شريط المتصفح',
    featureSame: 'نفس ميزات AgroCloud كما على الموقع',
    install: 'تثبيت التطبيق',
    installing: 'جار التثبيت…',
    notNow: 'ليس الآن',
    fabLabel: 'تثبيت التطبيق',
    iosStep1: 'اضغط «مشاركة» في شريط Safari',
    iosStep2: 'مرّر واختر «إضافة إلى الشاشة الرئيسية»',
    iosStep3: 'اضغط «إضافة» ثم افتح AgroCloud من الشاشة الرئيسية',
    ipadStep1: 'في Safari، اضغط «مشاركة» (مربع وسهم) في الشريط العلوي',
    ipadStep2: 'اختر «إضافة إلى الشاشة الرئيسية» من قائمة المشاركة',
    ipadStep3: 'تأكد من الاسم AgroCloud واضغط «إضافة»، ثم افتحه من الشاشة الرئيسية',
    iosSafariTitle: 'افتح في Safari للتثبيت',
    iosSafariSubtitle: 'على iPhone وiPad، «إضافة إلى الشاشة الرئيسية» تعمل في Safari فقط.',
    iosSafariStep1: 'انسخ رابط هذه الصفحة',
    iosSafariStep2: 'افتح Safari والصق الرابط في شريط العنوان',
    iosSafariStep3: 'اضغط مشاركة ← إضافة إلى الشاشة الرئيسية',
    copyLink: 'نسخ الرابط',
    copied: 'تم النسخ',
    androidStep1: 'اضغط قائمة (⋮) في Chrome',
    androidStep2: 'اختر «تثبيت التطبيق» أو «إضافة إلى الشاشة الرئيسية»',
    androidStep3: 'افتح AgroCloud من الشاشة الرئيسية — يعمل كتطبيق أصلي',
  },
} as const

export function usePwaInstallText(language: AppLanguage) {
  return pwaInstallText[language]
}
